version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: dev.dockerfile
    image: dev_conto_auth
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
